// Build Python from existing scripts. Agents pick up your scripts through the
// registered MCP servers and generate Python in that context. The output is a
// deliverable — to RUN it against an environment, submit it via Jobs, where a
// human approves first (Studio never executes arbitrary Python itself).
import { useState } from "react";
import { api } from "../api";

export default function PyBuild({ onClose }) {
  const [prompt, setPrompt] = useState("");
  const [context, setContext] = useState("");
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState(null); // {python, mode, mcp_servers, note}
  const [error, setError] = useState("");

  async function build() {
    if (!prompt.trim() || busy) return;
    setBusy(true);
    setError("");
    try {
      const d = await api("/python/build", {
        method: "POST",
        body: JSON.stringify({ prompt: prompt.trim(), context: context.trim() || undefined }),
      });
      setResult(d);
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="dashboard">
      <div className="canvas-head">
        <div>
          <div className="canvas-title">Build Python</div>
          <div className="meta">
            The agent picks up your existing scripts through registered MCP servers
            and builds Python in that style. To run it on an environment, submit it via Jobs.
          </div>
        </div>
        <div className="canvas-actions">
          <button className="chip" onClick={onClose}>✕ close</button>
        </div>
      </div>

      {error && <div className="error">{error}</div>}

      <label className="meta sqllab-label">What should the Python do?</label>
      <input
        className="sqllab-prompt"
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        onKeyDown={(e) => e.key === "Enter" && build()}
        placeholder="e.g. incremental load from S3 to the warehouse with a watermark"
      />
      <label className="meta sqllab-label">Existing script for context (optional)</label>
      <textarea
        className="gov-yaml"
        style={{ minHeight: 120 }}
        value={context}
        onChange={(e) => setContext(e.target.value)}
        spellCheck={false}
        placeholder="Paste a script the agent should follow the style of — or register an MCP scripts server so it reads them automatically."
      />

      <div className="gov-actions">
        <button className="chip chip-on" onClick={build} disabled={busy || !prompt.trim()}>
          {busy ? "building…" : "⚙ build Python"}
        </button>
        {result && (
          <button className="chip" onClick={() => navigator.clipboard?.writeText(result.python)}>
            ⧉ copy
          </button>
        )}
      </div>

      {result && (
        <>
          <div className="meta" style={{ margin: "6px 0" }}>
            {result.mode === "agent" ? "Generated by the agent" : "Scaffold (no LLM key)"}
            {result.mcp_servers?.length > 0
              ? ` · MCP context: ${result.mcp_servers.join(", ")}`
              : " · no MCP scripts server registered"}
            {result.note ? ` · ${result.note}` : ""}
          </div>
          <pre className="query-sql" style={{ whiteSpace: "pre", maxHeight: 480, overflow: "auto" }}>
            {result.python}
          </pre>
        </>
      )}
    </section>
  );
}
